### ISSUE TITLE
struttura

### ISSUE THREAD

**Issue by ermx** [codicepulito/data-driven-components#1]
Una prima astrazione che vedo utile sul progetto è quella di unificare la struttura delle pagine.
Invece di prevedere 2 tipi di pagine (datatable e form) sarebbe utile prevedere solo form e i datatable vederli come componenti della form (da poter quindi piazzare dove si ritiene più opportuno).
Anche il codice di rendering migliorerebbe non dovendo più distinguere tra le 2 possibilità.

**Comment by gianlucaciarcelluti** [comment]
#@ermx 
now you can use datatable as field type ;-)
as soon I can, I'll update docs and demo.
fell free to test it and let me know if it work as you espect. #
